export type IntegrationService = {
  id: string;
  name: string;
  description: string;
  logo: string;
};

export type IntegrationConnection = {
  id: string;
  integrationId: string;
  integrationName: string;
  integrationLogo: string;
  name: string;
  source: 'Carbon' | 'Utility';
  entityGroup: string;
  interval: string;
};

export const integrationServices: IntegrationService[] = [
  {
    id: 'amazon-quicksight',
    name: 'Amazon QuickSight',
    description: 'Amazon BI service to create dashboards and interactive visualisations.',
    logo: '/images/amazon_quicksight_logo.png',
  },
  {
    id: 'kafka',
    name: 'Kafka',
    description: 'Real-time data streaming, event-driven architectures and messaging systems.',
    logo: '/images/kafka_logo.png',
  },
  {
    id: 'power-bi',
    name: 'Power BI',
    description: 'Microsoft BI service to create dashboards and data visualisations.',
    logo: '/images/powerbi_logo.png',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Automation tool that connects various apps and services to automate workflows.',
    logo: '/images/zapier_logo.png',
  },
  {
    id: 'tableau',
    name: 'Tableau',
    description: 'BI service that helps seeing and transforming data into actionable insights.',
    logo: '/images/tableau_logo.png',
  },
  {
    id: 'measurabl',
    name: 'Measurabl',
    description: 'Enable the push and pull of data to and from Measurabl via an API.',
    logo: '/images/measurabl_logo.png',
  },
];

export const integrationConnections: IntegrationConnection[] = [
  {
    id: 'qs-energy',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Energy',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Energy',
    interval: '-',
  },
  {
    id: 'qs-logistics',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Logistics',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Logistics',
    interval: '-',
  },
  {
    id: 'qs-operations',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Operations',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Operations',
    interval: '-',
  },
  {
    id: 'qs-electricity-tou',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Electricity ToU',
    source: 'Utility',
    entityGroup: '135 Albert St - Electricity',
    interval: 'ToU',
  },
  {
    id: 'qs-water',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Water',
    source: 'Utility',
    entityGroup: '135 Albert St - Water',
    interval: 'Monthly',
  },
  {
    id: 'kafka-abc',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'ABC Group LTD',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD',
    interval: '-',
  },
  {
    id: 'zapier-abc',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'ABC Group LTD',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD',
    interval: '-',
  },
  {
    id: 'zapier-gas',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: '135 Albert St - Gas',
    source: 'Utility',
    entityGroup: '135 Albert St - Gas',
    interval: 'Yearly',
  },
  ,
  {
    id: 'amazon-quicksight-009',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Energy Sync 009',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 009',
    interval: '-',
  },
  {
    id: 'kafka-010',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Logistics Hub 010',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 010',
    interval: 'Monthly',
  },
  {
    id: 'power-bi-011',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Operations Flow 011',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 011',
    interval: 'Yearly',
  },
  {
    id: 'zapier-012',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Water Meter 012',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 012',
    interval: 'ToU',
  },
  {
    id: 'tableau-013',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Emission Track 013',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 013',
    interval: 'Weekly',
  },
  {
    id: 'measurabl-014',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Asset Stream 014',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 014',
    interval: '-',
  },
  {
    id: 'amazon-quicksight-015',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Facilities Core 015',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 015',
    interval: 'Monthly',
  },
  {
    id: 'kafka-016',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Utility Bridge 016',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 016',
    interval: 'Yearly',
  },
  {
    id: 'power-bi-017',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Carbon Ledger 017',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 017',
    interval: 'ToU',
  },
  {
    id: 'zapier-018',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Sustain Ops 018',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 018',
    interval: 'Weekly',
  },
  {
    id: 'tableau-019',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Grid Monitor 019',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 019',
    interval: '-',
  },
  {
    id: 'measurabl-020',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Fleet Pulse 020',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 020',
    interval: 'Monthly',
  },
  {
    id: 'amazon-quicksight-021',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Warehouse Link 021',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 021',
    interval: 'Yearly',
  },
  {
    id: 'kafka-022',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Site Vision 022',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 022',
    interval: 'ToU',
  },
  {
    id: 'power-bi-023',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Cooling Plant 023',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 023',
    interval: 'Weekly',
  },
  {
    id: 'zapier-024',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Solar Intake 024',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 024',
    interval: '-',
  },
  {
    id: 'tableau-025',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Waste Stream 025',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 025',
    interval: 'Monthly',
  },
  {
    id: 'measurabl-026',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Supply Chain 026',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 026',
    interval: 'Yearly',
  },
  {
    id: 'amazon-quicksight-027',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Vendor Sync 027',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 027',
    interval: 'ToU',
  },
  {
    id: 'kafka-028',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'HVAC Feed 028',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 028',
    interval: 'Weekly',
  },
  {
    id: 'power-bi-029',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Usage Index 029',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 029',
    interval: '-',
  },
  {
    id: 'zapier-030',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Meter Connect 030',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 030',
    interval: 'Monthly',
  },
  {
    id: 'tableau-031',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Demand Watch 031',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 031',
    interval: 'Yearly',
  },
  {
    id: 'measurabl-032',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Plant Insights 032',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 032',
    interval: 'ToU',
  },
  {
    id: 'amazon-quicksight-033',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Energy Sync 033',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 033',
    interval: 'Weekly',
  },
  {
    id: 'kafka-034',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Logistics Hub 034',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 034',
    interval: '-',
  },
  {
    id: 'power-bi-035',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Operations Flow 035',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 035',
    interval: 'Monthly',
  },
  {
    id: 'zapier-036',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Water Meter 036',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 036',
    interval: 'Yearly',
  },
  {
    id: 'tableau-037',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Emission Track 037',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 037',
    interval: 'ToU',
  },
  {
    id: 'measurabl-038',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Asset Stream 038',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 038',
    interval: 'Weekly',
  },
  {
    id: 'amazon-quicksight-039',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Facilities Core 039',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 039',
    interval: '-',
  },
  {
    id: 'kafka-040',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Utility Bridge 040',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 040',
    interval: 'Monthly',
  },
  {
    id: 'power-bi-041',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Carbon Ledger 041',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 041',
    interval: 'Yearly',
  },
  {
    id: 'zapier-042',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Sustain Ops 042',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 042',
    interval: 'ToU',
  },
  {
    id: 'tableau-043',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Grid Monitor 043',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 043',
    interval: 'Weekly',
  },
  {
    id: 'measurabl-044',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Fleet Pulse 044',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 044',
    interval: '-',
  },
  {
    id: 'amazon-quicksight-045',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Warehouse Link 045',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 045',
    interval: 'Monthly',
  },
  {
    id: 'kafka-046',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Site Vision 046',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 046',
    interval: 'Yearly',
  },
  {
    id: 'power-bi-047',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Cooling Plant 047',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 047',
    interval: 'ToU',
  },
  {
    id: 'zapier-048',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Solar Intake 048',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 048',
    interval: 'Weekly',
  },
  {
    id: 'tableau-049',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Waste Stream 049',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 049',
    interval: '-',
  },
  {
    id: 'measurabl-050',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Supply Chain 050',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 050',
    interval: 'Monthly',
  },
  {
    id: 'amazon-quicksight-051',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Vendor Sync 051',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 051',
    interval: 'Yearly',
  },
  {
    id: 'kafka-052',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'HVAC Feed 052',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 052',
    interval: 'ToU',
  },
  {
    id: 'power-bi-053',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Usage Index 053',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 053',
    interval: 'Weekly',
  },
  {
    id: 'zapier-054',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Meter Connect 054',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 054',
    interval: '-',
  },
  {
    id: 'tableau-055',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Demand Watch 055',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 055',
    interval: 'Monthly',
  },
  {
    id: 'measurabl-056',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Plant Insights 056',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 056',
    interval: 'Yearly',
  },
  {
    id: 'amazon-quicksight-057',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Energy Sync 057',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 057',
    interval: 'ToU',
  },
  {
    id: 'kafka-058',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Logistics Hub 058',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 058',
    interval: 'Weekly',
  },
  {
    id: 'power-bi-059',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Operations Flow 059',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 059',
    interval: '-',
  },
  {
    id: 'zapier-060',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Water Meter 060',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 060',
    interval: 'Monthly',
  },
  {
    id: 'tableau-061',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Emission Track 061',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 061',
    interval: 'Yearly',
  },
  {
    id: 'measurabl-062',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Asset Stream 062',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 062',
    interval: 'ToU',
  },
  {
    id: 'amazon-quicksight-063',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Facilities Core 063',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 063',
    interval: 'Weekly',
  },
  {
    id: 'kafka-064',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Utility Bridge 064',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 064',
    interval: '-',
  },
  {
    id: 'power-bi-065',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Carbon Ledger 065',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 065',
    interval: 'Monthly',
  },
  {
    id: 'zapier-066',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Sustain Ops 066',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 066',
    interval: 'Yearly',
  },
  {
    id: 'tableau-067',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Grid Monitor 067',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 067',
    interval: 'ToU',
  },
  {
    id: 'measurabl-068',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Fleet Pulse 068',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 068',
    interval: 'Weekly',
  },
  {
    id: 'amazon-quicksight-069',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Warehouse Link 069',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 069',
    interval: '-',
  },
  {
    id: 'kafka-070',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Site Vision 070',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 070',
    interval: 'Monthly',
  },
  {
    id: 'power-bi-071',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Cooling Plant 071',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 071',
    interval: 'Yearly',
  },
  {
    id: 'zapier-072',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Solar Intake 072',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 072',
    interval: 'ToU',
  },
  {
    id: 'tableau-073',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Waste Stream 073',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 073',
    interval: 'Weekly',
  },
  {
    id: 'measurabl-074',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Supply Chain 074',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 074',
    interval: '-',
  },
  {
    id: 'amazon-quicksight-075',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Vendor Sync 075',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 075',
    interval: 'Monthly',
  },
  {
    id: 'kafka-076',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'HVAC Feed 076',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 076',
    interval: 'Yearly',
  },
  {
    id: 'power-bi-077',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Usage Index 077',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 077',
    interval: 'ToU',
  },
  {
    id: 'zapier-078',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Meter Connect 078',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 078',
    interval: 'Weekly',
  },
  {
    id: 'tableau-079',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Demand Watch 079',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 079',
    interval: '-',
  },
  {
    id: 'measurabl-080',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Plant Insights 080',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 080',
    interval: 'Monthly',
  },
  {
    id: 'amazon-quicksight-081',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Energy Sync 081',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 081',
    interval: 'Yearly',
  },
  {
    id: 'kafka-082',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Logistics Hub 082',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 082',
    interval: 'ToU',
  },
  {
    id: 'power-bi-083',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Operations Flow 083',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 083',
    interval: 'Weekly',
  },
  {
    id: 'zapier-084',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Water Meter 084',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 084',
    interval: '-',
  },
  {
    id: 'tableau-085',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Emission Track 085',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 085',
    interval: 'Monthly',
  },
  {
    id: 'measurabl-086',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Asset Stream 086',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 086',
    interval: 'Yearly',
  },
  {
    id: 'amazon-quicksight-087',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Facilities Core 087',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 087',
    interval: 'ToU',
  },
  {
    id: 'kafka-088',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Utility Bridge 088',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 088',
    interval: 'Weekly',
  },
  {
    id: 'power-bi-089',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Carbon Ledger 089',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 089',
    interval: '-',
  },
  {
    id: 'zapier-090',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Sustain Ops 090',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 090',
    interval: 'Monthly',
  },
  {
    id: 'tableau-091',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Grid Monitor 091',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 091',
    interval: 'Yearly',
  },
  {
    id: 'measurabl-092',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Fleet Pulse 092',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 092',
    interval: 'ToU',
  },
  {
    id: 'amazon-quicksight-093',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Warehouse Link 093',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 093',
    interval: 'Weekly',
  },
  {
    id: 'kafka-094',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'Site Vision 094',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 094',
    interval: '-',
  },
  {
    id: 'power-bi-095',
    integrationId: 'power-bi',
    integrationName: 'Power BI',
    integrationLogo: '/images/powerbi_logo.png',
    name: 'Cooling Plant 095',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 095',
    interval: 'Monthly',
  },
  {
    id: 'zapier-096',
    integrationId: 'zapier',
    integrationName: 'Zapier',
    integrationLogo: '/images/zapier_logo.png',
    name: 'Solar Intake 096',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 096',
    interval: 'Yearly',
  },
  {
    id: 'tableau-097',
    integrationId: 'tableau',
    integrationName: 'Tableau',
    integrationLogo: '/images/tableau_logo.png',
    name: 'Waste Stream 097',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 097',
    interval: 'ToU',
  },
  {
    id: 'measurabl-098',
    integrationId: 'measurabl',
    integrationName: 'Measurabl',
    integrationLogo: '/images/measurabl_logo.png',
    name: 'Supply Chain 098',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 098',
    interval: 'Weekly',
  },
  {
    id: 'amazon-quicksight-099',
    integrationId: 'amazon-quicksight',
    integrationName: 'Amazon QuickSight',
    integrationLogo: '/images/amazon_quicksight_logo.png',
    name: 'Vendor Sync 099',
    source: 'Carbon',
    entityGroup: 'ABC Group LTD - Group 099',
    interval: '-',
  },
  {
    id: 'kafka-100',
    integrationId: 'kafka',
    integrationName: 'Kafka',
    integrationLogo: '/images/kafka_logo.png',
    name: 'HVAC Feed 100',
    source: 'Utility',
    entityGroup: 'ABC Group LTD - Group 100',
    interval: 'Monthly',
  },
];

export async function fetchIntegrationServices(): Promise<IntegrationService[]> {
  return Promise.resolve(integrationServices);
}

type FetchConnectionsOptions = {
  search?: string;
  page?: number;
  pageSize?: number;
};

export async function fetchIntegrationConnections(
  options: FetchConnectionsOptions = {},
): Promise<{ items: IntegrationConnection[]; total: number }> {
  // Simulate loading state
  await new Promise((resolve) => setTimeout(resolve, 2000));

  const query = options.search?.trim().toLowerCase();
  const filtered = query
    ? integrationConnections.filter(
        (connection) =>
          connection.name.toLowerCase().includes(query) ||
          connection.integrationName.toLowerCase().includes(query) ||
          connection.entityGroup.toLowerCase().includes(query),
      )
    : integrationConnections;

  const pageSize = options.pageSize ?? filtered.length;
  const page = options.page ?? 1;
  const startIndex = (page - 1) * pageSize;
  const items = filtered.slice(startIndex, startIndex + pageSize);

  return Promise.resolve({ items, total: filtered.length });
}
